Repository cwtickle/danoniplus, pull requests merged in 2020-01, with the labels that each got.

#583 [0138-undefined-creator] 譜面名未指定のときにリザルトコピー時のクレジットがundefinedになる問題を修正
  js/danoni_main.js
Labels: bug, func:Result

#584 [ver11.2.0] キーブロックする処理の見直し　他
  js/danoni_main.js
Labels: bug, func:Result

#585 [0139-code-refactoring] メイン画面初期化のコード整理
  js/danoni_main.js
Labels: func:Main

#586 [ver11.2.1] コード見直し、judgement:OFFで判定部分が消えない問題を修正
  SECURITY.md
  js/danoni_main.js
Labels: func:Main

#589 速度変化の遷移グラフを表示する機能を作成
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#590 [0143-load-dos-refactoring] loadDos関数の整理、速度グラフ表示の分割dos対応
  js/danoni_main.js
Labels: func:Settings

#588 [0141-code-refactoring] リザルト画面のコード整理
  js/danoni_main.js
Labels: func:Result

#591 [0144/prepared-score-details] 計算誤差対応、速度グラフの拡張フォント対応
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#592 [0145/density-graph] 譜面密度グラフの作成
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#594 [0146/customjs-refactoring] loadCustomjsのコード整理
  js/danoni_main.js
Labels: func:Loading

#593 [ver11.3.0] 速度変化・譜面密度グラフの追加、コード整理
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Result, func:Settings

#595 [0147/fix-graph] 最大密度に色が付かない問題を修正
  js/danoni_main.js
Labels: bug, func:Settings

#596 [ver11.3.1] 最大密度に色が付かない問題を修正
  js/danoni_main.js
Labels: bug, func:Settings
