Repository cwtickle/danoniplus, pull requests merged in 2020-02, with the labels that each got.

#597 [0143/graph-details] 速度変化数・プレイ時間・APMの表示対応
  js/danoni_main.js
Labels: func:Settings

#598 [ver11.4.0] 譜面明細画面に補足情報を追加
  js/danoni_main.js
Labels: func:Settings

#599 [0150/preload-dos] 速度変化、譜面密度関連のデータを事前読込へ変更
  js/danoni_main.js
Labels: func:Settings, func:Title

#600 [0151/preload-dos] scoreConvert関数が譜面番号依存だった問題を修正
  js/danoni_main.js
Labels: bug, func:Loading

#602 ツール難易度測定機能の移植
  js/danoni_main.js
Labels: func:Settings

#604 [0154/include-dif-tools] レベル計算ツールのデザイン修正
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#601 [0152/color-gradation] 色変化のグラデーションに対応
  js/danoni_main.js
Labels: func:Main, func:Title

#605 [ver12.0.0] 矢印色のグラデーション実装、レベル計算ツール++移植
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Main, func:Settings, func:Title

#606 [0155/color-gradation] setColorの1・3番目に方向が指定された場合の問題を修正
  js/danoni_main.js
Labels: bug, func:Title

#607 [0156/synchronized-loading-dos] 譜面詳細用データを全て読み込んでからタイトルへ移動するよう変更
  js/danoni_main.js
Labels: bug, func:Title

#608 [0157/fix-dif-tools] レベル計算中の無効な値を対象にしないよう修正
  js/danoni_main.js
Labels: bug, func:Settings

#609 [ver12.0.1] 色変化・ツール計算部分の問題修正
  SECURITY.md
  js/danoni_main.js
Labels: bug, func:Settings, func:Title

#610 [0158/color-type-reset] KeyConfigでColorType利用時の不具合を修正
  js/danoni_main.js
Labels: bug, func:KeyConfig

#611 [ver12.0.2] 矢印グラデーションを利用時、KeyConfig関連の不具合を修正
  js/danoni_main.js
Labels: bug, func:KeyConfig

#614 [0161/main-sprite-expansion] 矢印描画サイズを可変にする設定を追加
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig, func:Main

#615 [ver12.1.0] 矢印描画サイズを可変にする設定を追加
  SECURITY.md
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig, func:Main

#616 [0162/score-override] スコア上書きのためにハイスコア差分が計算されない問題を修正
  js/danoni_main.js
Labels: func:Result

#617 [ver12.1.1] スコア上書き時ハイスコア差分が計算されない問題を修正
  SECURITY.md
  js/danoni_main.js
Labels: bug, func:Result

#618 titlegrdが1行分だけ指定されているとき2行目が表示されない問題の修正
  js/danoni_main.js
Labels: bug, func:Title

#619 [ver12.1.2] titlegrdが1行分だけ指定されているとき曲名の2行目が表示されない問題の修正
  SECURITY.md
  js/danoni_main.js
Labels: bug, func:Title
