Repository cwtickle/danoniplus, pull requests merged in 2020-12, with the labels that each got.

#904 [0312/title-animation] タイトル文字のアニメーションを１・２行目で分離
  css/danoni_main.css
  danoni/danoni0.html
  danoni/danoni1.html
  js/danoni_main.js
  js/danoni_setting.js
Labels: func:Title

#905 [0313/transkey-9] 9A/9Bkeyの別キーモード時の配色を一部変更
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#906 [0314/preload-firefox] Firefoxで画像のプリロードを有効にする変更
  js/danoni_main.js
Labels: func:Loading

#908 曲終了直後にリトライキーを押すとALL0のリザルトが表示される問題の修正
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer.

#910 [0315/gauge-heavy] ライフ制ゲージ設定にHeavyを追加、ゲージ設定順序の見直し
  js/danoni_main.js
Labels: func:Settings

#913 [0317/preload-firefox] 追加した画像ファイルがある場合、Firefoxでプレイできない問題を修正
  js/danoni_main.js
Labels: bug, func:Loading

#916 [0319/onigiri-color-type2] ColorType: 2のおにぎりの初期色を白から薄青に変更
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#917 [0320/customjs-duplicated] customjsを二重読込している問題を修正
  js/danoni_main.js
Labels: bug, func:Loading, need-to-fix-supportVer.

#920 [0321/gitter-link] 結果画面にGitterへのリンクを追加
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Result

#922 [0322/image-extensions] 画像拡張子指定時に画像読込チェックに失敗する問題を修正
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: bug, func:Loading
