Repository cwtickle/danoniplus, pull requests merged in 2020-08, with the labels that each got.

#783 [0249/convert-keycode] KeyboardEvent.code対応
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Main, help wanted

#788 [0251/lifeinit-decimal] ライフ初期値の小数対応
  js/danoni_main.js
Labels: func:Settings

#790 [0252/playing-width] ゲームエリアのX軸調整機能の実装
  js/danoni_main.js
Labels: func:Main

#793 [0253/shift-delete] Shift+Deleteキーの組み合わせが利かない問題を修正
  js/danoni_main.js
Labels: bug, func:Main

#797 [0254/code-semicolon] セミコロンが使用できない問題を修正
  js/lib/danoni_constants.js
Labels: bug, func:KeyConfig

#799 [0255/code-numpad] テンキーの割り当てミスを修正
  js/lib/danoni_constants.js
Labels: bug, func:KeyConfig

#801 [0256/code-blacket] コード割り当てミスを修正
  js/lib/danoni_constants.js
Labels: bug, func:KeyConfig

#810 リトライ時に稀に早回しになる不具合の修正 +α
  js/danoni_main.js
Labels: bug, func:Loading

#811 [0259/fix-keydown] 結果画面のキーコード置換漏れを修正
  js/danoni_main.js
Labels: bug, func:Result

#812 [0260/color-upper20] 20個以上のキーに対する色変化対応（単発矢印・個別）
  js/danoni_main.js
Labels: func:Main

#813 [0261/result-format] リザルトデータ用フォーマットの実装
  js/danoni_main.js
  js/danoni_setting.js
Labels: func:Result

#815 [0262/fix-resultdata] スコアをカスタムした際にリザルトデータへ反映されない問題を修正
  js/danoni_main.js
Labels: bug, func:Result
