Repository cwtickle/danoniplus, pull requests merged in 2021-10, with the labels that each got.

#1125 キーコンフィグ画面にプレイボタン追加
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1131 [0461/lyrics-white] word_dataの初期色をCSSに任せる設定に変更
  js/danoni_main.js
Labels: func:Main

#1134 [0462/chart-sorting] 矢印データが昇順で無い場合の問題を修正
  js/danoni_main.js
Labels: bug, func:Loading, need-to-fix-supportVer.

#1149 [0471/warning-window] Firefox時、警告ウィンドウが最小化される問題を修正
  js/danoni_main.js
Labels: bug, func:Title, func:KeyConfig, func:Result
