Repository cwtickle/danoniplus, pull requests merged in 2021-04, with the labels that each got.

#1036 [0396/file-loading] ファイルロード時のg_loadObjの管理方法を一部変更
  js/danoni_main.js
Labels: func:Loading

#1040 [0400/keyconfig-button] キーコンフィグの対応キー箇所をボタン化
  js/danoni_main.js
  js/lib/danoni_constants.js
  skin/danoni_skin_default.css
  skin/danoni_skin_light.css
  skin/danoni_skin_skyblue.css
Labels: func:KeyConfig

#1041 [0401/cr-keys] キー数周りのコード整理
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1042 [0402/extra-keys] 特殊キーのキーコンフィグのリセットに失敗する問題を修正
  js/danoni_main.js
Labels: bug, func:KeyConfig

#1044 空の矢印データを含む譜面にS-Ranをかけるとフルコン演出が通常より早く出てしまう問題の修正
  js/danoni_main.js
Labels: bug, need-to-fix-supportVer.

#1045 [0404/empty-score] #1044 に対するコード見直し
  js/danoni_main.js
Labels: func:Loading

#1048 [0405/white-keycon-color] 明背景時、キーコンフィグ画面の文字が薄い問題を修正
  js/danoni_main.js
Labels: bug, func:KeyConfig

#1053 [0408/ctrl-c] タイトル・結果画面でCtrl+Cを使うとショートカットキーが動作する問題を修正
  js/lib/danoni_constants.js
Labels: func:Result, func:Title

#1052 [0407/switch-scoredetail] 譜面明細表示の逆回しに対応
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1056 [0411/switch-right-click] Save切替ボタン、Display切替ボタンの右クリック対応
  js/danoni_main.js
Labels: func:Settings

#1059 [0413/shuffle-expansion] シャッフルグループの複数化対応（通常キー）
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1060 [0414/temp-color-change] 一時的に初期矢印色の割当先を変更できる機能を実装
  js/danoni_main.js
Labels: func:KeyConfig

#1061 [0415/cr-common] 共通部分のコード整理
  js/danoni_main.js
Labels: code-refactoring

#1062 [0416/legacy-func] 非推奨関数をlegacy_functionへ移動
  js/danoni_main.js
  js/lib/danoni_legacy_function.js
Labels: code-refactoring

#1064 [0417/shuffle-name] シャッフルグループが複数の場合のRandom+/S-Random+表記を統一
  js/danoni_main.js
Labels: func:Result
