Repository cwtickle/danoniplus, pull requests merged in 2021-09, with the labels that each got.

#1096 Adjustmentを0.1単位で設定できる機能の追加
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1098 [0440/localfile-msg] ファイル直接起動かつ音源がエンコード無しのとき警告メッセージを表示するよう変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Title

#1099 [0441/adjustment-layout] Adjustment周りの見た目部分の調整
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1097 [0439/multi-imgtypes] デフォルト画像セットの複数化に対応（サーバー専用）
  img/classic/arrow.png
  js/danoni_main.js
  js/danoni_setting.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1102 [0442/decimal-adjustment] 譜面データが極端に小さいフレーム数のときにAdjが一部利かない問題を修正
  js/danoni_main.js
Labels: bug, func:Main, func:Loading

#1104 プレイ開始ボタンなどのショートカットにテンキーエンターを割り当て
  js/lib/danoni_constants.js
Labels: func:Title, func:Settings, func:Result

#1105 [0443/imgtype-org] ImgType: Original の位置を自由な位置に入れられるよう変更
  js/danoni_main.js
  js/danoni_setting.js
Labels: func:KeyConfig

#1106 [0444/transkey-7i] 7keyの別キーモードとして7ikeyを追加
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1108 [0445/imgtype-notes] ノートスキンの追加、デフォルト画像を回転させないオプションを追加
  img/classic/arrowShadow.png
  img/imgbase/arrowShadow_classic.ai
  img/note/aaShadow.svg
  img/note/arrow.svg
  img/note/arrowShadow.svg
  img/note/borderline.svg
  img/note/c.svg
  img/note/cursor.svg
  img/note/frzbar.svg
  img/note/giko.svg
  img/note/iyo.svg
  img/note/monar.svg
  img/note/morara.svg
  img/note/onigiri.svg
  js/danoni_main.js
  js/danoni_setting.js
  js/lib/danoni_constants.js
Labels: func:Main, func:KeyConfig

#1110 フリーズアローの挙動見直し
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer.

#1111 [0446/boost-frames] Boost時の軌道計算を見直し
  js/danoni_main.js
Labels: func:Settings, need-to-fix-supportVer.

#1114 [0448/adj-setting] 設定画面のAdjustmentボタン・ショートカットキー仕様変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1116 [0449/msg-setting] Adjustmentのオンマウス説明文の修正、コード修正
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: bug, func:Settings

#1117 [0450/key-patterns] 12, 14keyにキーパターン追加、14keyのシャッフルグループ削除
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1120 [0452/rev-shortcut] ReverseのショートカットをRキー、Scrollのショートカットを上下キーに変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: bug, func:Settings, need-to-fix-supportVer.

#1121 [0453/rev-shortcut2] main側ではbtnAddFuncを明示的に使わないよう修正
  js/danoni_main.js
Labels: func:Settings, need-to-fix-supportVer.

#1123 [0454/AP-rank] ランクAPの実装
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Result

#1124 [0455/difficulty-name] プレイ画面に譜面名を追加、曲名長に合わせて文字サイズを調整
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Title, func:Main

#1126 [0456/musicinfo] プレイ画面のクレジット位置を微調整（以前の位置に戻す）
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Main

#1127 [0457/fontsize] バージョン名のフォントサイズを調整できるよう変更
  js/danoni_main.js
Labels: func:Title

#1128 [0458/keyname] カスタムキーの名前を変更できる機能を追加
  js/danoni_main.js
Labels: func:Settings, func:Main, func:Result
