Repository cwtickle/danoniplus, pull requests merged in 2021-01, with the labels that each got.

#927 [0324/ttile-expansion] タイトルアニメーションの設定を拡張（クラス設定他）
  js/danoni_main.js
Labels: func:Title

#929 同一レーン上に通常矢印とフリーズアローが短い間隔で存在するとき、通常矢印の判定が優先されてしまう現象を修正
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer.

#930 [0325/judge-arrow-frz] PR #929 の再修正
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer.

#932 [0326/judge-keydown] 空押し時のヒットモーションが一部動かない問題を修正
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer.

#933 AppearanceとOpacityの初期値設定処理を修正
  js/danoni_main.js
Labels: bug, func:Settings

#937 [0329/gauge-initial] gaugeXの設定補完に対応
  js/danoni_main.js
Labels: func:Settings

#940 [0331/custom-gauge-list] danoni_setting.jsにカスタムゲージリストを追加
  js/danoni_main.js
  js/danoni_setting.js
Labels: func:Settings

#942 [0332/title-arrow-opacity] タイトルの背景矢印の透明度設定を有効化
  js/danoni_main.js
Labels: func:Title
