Repository cwtickle/danoniplus, pull requests merged in 2021-03, with the labels that each got.

#1006 [0376/code-refactoring] キーコンフィグ画面内のeval関数を排除
  js/danoni_main.js
Labels: func:KeyConfig

#1009 Base64エンコードした曲データを直接デコードする
  js/danoni_main.js
Labels: func:Loading, need-to-fix-supportVer.

#1011 [0379/colorgrd-init] グラデーション変数の初期化漏れを修正
  js/danoni_main.js
Labels: bug

#1014 [0381/titlegrd] グラデーションにdeg/radなどが入っているときに文字が表示されない問題を修正
  js/danoni_main.js
Labels: bug

#1016 [0382/cr-difinfo] レベル計算ツール周りのコード整理
  js/danoni_main.js
Labels: func:Settings

#1018 [0384/cr-keyconfig] キーコンフィグ周りのコード整理
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1013 [0380/dif-shortcut] 譜面セレクター表示時に関する仕様変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1024 [0389/multi-custom-gauge2] customGaugeの複数譜面対応、デフォルト値対応(事前設定版)　他
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1027 [0391/customg-default] カスタムゲージのデフォルト値設定の見直し
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1032 [0393/display-save] データセーブフラグ切替ボタンをDisplay画面にも表示
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings
