Repository cwtickle/danoniplus, pull requests merged in 2022-11, with the labels that each got.

#1350 fix: [0609] クレジットリンク表示の折り返しが利かない問題を修正
  js/danoni_main.js
Labels: bug, func:Title

#1352 [0612] フリーズアロー（始点）に対してFast/Slowを常時カウントするよう変更
  js/danoni_main.js
Labels: func:Main

#1353 refactor: [0611] コードの整理
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Title, func:Loading, code-refactoring

#1355 feat: [0613] フリーズアローの始点判定範囲を拡大
  js/danoni_main.js
Labels: func:Main

#1357 リタイア時にもクリア判定を行うように変更
  js/danoni_main.js
Labels: func:Main

#1358 feat: [0614] 曲名、アーティスト名の多言語対応
  js/danoni_main.js
Labels: func:Title

#1359 refactor: [0615] changeJudgeCharacterの引数名を見直し
  js/danoni_main.js
Labels: code-refactoring

#1361 feat: [0616] fast/slowのカウンターと表示関数を統一
  js/danoni_main.js
Labels: func:Main, code-refactoring

#1362 feat: [0617] 制作者クレジットについて多言語表記に対応
  js/danoni_main.js
Labels: func:Title

#1365 feat: [0619] タイトル文字関連の多言語表示対応 及び コード整理
  js/danoni_main.js
Labels: func:Title, code-refactoring

#1364 improve: [0618] シャッフル設定が無効もしくは一部無効のとき、表示メッセージを変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1366 refactor: [0620] 矢印・フリーズアロー処理部分のコード整理
  js/danoni_main.js
Labels: bug, func:Main, need-to-fix-supportVer., code-refactoring
