Repository cwtickle/danoniplus, pull requests merged in 2023-06, with the labels that each got.

#1497 improve: [0707] 一部キーのデフォルトカラー・シャッフルグループを変更
  js/lib/danoni_constants.js
Labels: func:KeyConfig

#1498 fix: [0708] 矢印数がゼロの場合にツール値がNaNになる問題を修正
  js/danoni_main.js
Labels: bug, func:Settings, need-to-fix-supportVer.

#1500 feat: [0709] ゲージ詳細部分の仕様変更
  css/danoni_main.css
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1502 fix: [0710] オンマウスでのコメント間違いを修正
  js/lib/danoni_constants.js
Labels: bug, func:Settings

#1504 improve: [0711] 譜面明細表示の順番、名称を変更
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Settings

#1503 空押し判定を実装
  js/danoni_main.js
  js/lib/danoni_constants.js
  js/template/danoni_setting.js
  skin/danoni_skin_default.css
  skin/danoni_skin_light.css
  skin/danoni_skin_skyblue.css
Labels: func:Settings, func:Main, func:Result

#1505 improve: [0712] Excessiveの名前をconstantsから変更できるよう対応
  js/danoni_main.js
  js/lib/danoni_constants.js
Labels: func:Result

#1508 improve: [0714] フリーズ始点判定有効時、DifLevelでの矢印数表記を一部変更
  css/danoni_main.css
  js/danoni_main.js
Labels: func:Settings

#1509 improve: [0715] Difficultyを変更するごとにGaugeを初期化しないよう変更
  js/danoni_main.js
Labels: func:Settings, code-refactoring
